#pragma once

#define DIRECTORSCUT_VERSION_MAJOR 0
#define DIRECTORSCUT_VERSION_MINOR 1
#define DIRECTORSCUT_VERSION_PATCH 0
#define DIRECTORSCUT_VERSION_BUILD 0
#define STRINGIFY(x) #x
#define DIRECTORSCUT_VERSION_STRING STRINGIFY(DIRECTORSCUT_VERSION_MAJOR) "." STRINGIFY(DIRECTORSCUT_VERSION_MINOR) "." STRINGIFY(DIRECTORSCUT_VERSION_PATCH) "." STRINGIFY(DIRECTORSCUT_VERSION_BUILD)

#define DIRECTORSCUT_DEVELOPMENT_STAGE "Pre-Alpha"
